### ISSUE TITLE
wav header error

### ISSUE THREAD

**Issue by ambuu** [loonix/another_audio_recorder#3]
E/ExoPlayerImplInternal(12865): Source error
E/ExoPlayerImplInternal(12865):   com.google.android.exoplayer2.ParserException: Expected block size: 2; got: 1
E/ExoPlayerImplInternal(12865):       at com.google.android.exoplayer2.extractor.wav.WavExtractor$PassthroughOutputWriter.<init>(WavExtractor.java:222)
E/ExoPlayerImplInternal(12865):       at com.google.android.exoplayer2.extractor.wav.WavExtractor.read(WavExtractor.java:122)
E/ExoPlayerImplInternal(12865):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:982)
E/ExoPlayerImplInternal(12865):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
E/ExoPlayerImplInternal(12865):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/ExoPlayerImplInternal(12865):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/ExoPlayerImplInternal(12865):       at java.lang.Thread.run(Thread.java:764)

**Comment by loonix** [comment]
Hi, you give me no description of the issue, I have no idea what is that?

**Comment by lucas-sampaio-fluency** [comment]
@loonix 
Hi, I think I'm facing the same issue.
On Android my app is recording using the `.wav` format and the recording seems successful, however the Android audio player `exoplayer` is not able to play the audio file,  giving the following error:

```
E/ExoPlayerImplInternal(17567): Playback error
E/ExoPlayerImplInternal(17567):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(17567):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)
E/ExoPlayerImplInternal(17567):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:602)
E/ExoPlayerImplInternal(17567):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(17567):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal(17567):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(17567):   Caused by: com.google.android.exoplayer2.ParserException: Expected block size: 2; got: 1
E/ExoPlayerImplInternal(17567):       at com.google.android.exoplayer2.extractor.wav.WavExtractor$PassthroughOutputWriter.<init>(WavExtractor.java:308)
E/ExoPlayerImplInternal(17567):       at com.google.android.exoplayer2.extractor.wav.WavExtractor.readFormat(WavExtractor.java:202)
E/ExoPlayerImplInternal(17567):       at com.google.android.exoplayer2.extractor.wav.WavExtractor.read(WavExtractor.java:134)
E/ExoPlayerImplInternal(17567):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
E/ExoPlayerImplInternal(17567):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1039)
E/ExoPlayerImplInternal(17567):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal(17567):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(17567):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(17567):       at java.lang.Thread.run(Thread.java:923)
```

The same thing does not happen when using the `.m4a` format. It also does not happen on iOS.
So, I believe the problem is with the formatting of the `.wav` file, specifically on Android.

btw my app is using the [just_audio](https://pub.dev/packages/just_audio) lib to play the audio file.

**Comment by lucas-sampaio-fluency** [comment]
[This fix](https://github.com/rmbrone/flutter_audio_recorder/issues/11#issuecomment-654289094) works!
@loonix I suggest that you apply this change as well :)
