### ISSUE TITLE
Call not recording

### ISSUE THREAD

**Issue by pirate-007** [loonix/another_audio_recorder#7]
another_audio_recorder: ^1.0.1

When I record a phone call I can't hear the conversation between the users in that audio file

Android
version: 11

if use the another_audio_recorder package in the usual way( without recording a call) it works fine I can hear the recorded content in the audio file when I try to record a call during that time of the call I can't hear anything in the recorded file but the recording process Is Working

Code of recording function
 _start() async {
    print("recording");
    try {
      await _recorder?.start();
      var recording = await _recorder?.current(channel: 0);
      setState(() {
      });

      const tick = Duration(milliseconds: 50);
      Timer.periodic(tick, (Timer t) async {
        if (recording!.status == RecordingStatus.Stopped) {
          t.cancel();
        }

        var current = await _recorder?.current(channel: 0);
        // print(current.status);
        setState(() {
        });
      });
    } catch (e) {
      print(e);
    }
  }

**Comment by loonix** [comment]
so you want to record a call using this plugin? could you make en example app so I can quickly debug this issue?
